### ISSUE TITLE
Any way or how to to compile this for arm ? like raspberry ? 

### ISSUE THREAD

**Issue by halloulpsx** [soundanalogous/BreakoutServer#7]
Any way or how to to compile this for arm ? like raspberry ? 

Thank you

**Comment by soundanalogous** [comment]
If you can compile Java for Arm it will work. I don't personally know how to do it however.

**Comment by halloulpsx** [comment]
@soundanalogous thank you for your response, well i know that java is cross platform, but i did not know that support arm too. and i was able to run the breakoutserver on raspberry, i only had to point to the libtxrx & RXTXcomm.jar using this line : java -Djava.library.path=/usr/lib/jni -cp /usr/share/java/RXTXcomm.jar -jar breakouserver.jar

you should add it to your readme if you want ;) 

so i am closing this issue now.

Thank you very very much.
